//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doctor
{
    public partial class bill
    {
        /// <summary>
        /// Label1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
        /// Bill control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Bill;

        /// <summary>
        /// Button1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
